services:
  postgres-db:
    container_name: db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - twim-network
  mongo-db:
    container_name: db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./database/twim.js:/docker-entrypoint-initdb.d/twim.js:ro
    networks:
      - twim-network
  twim:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: twim
      restart: always
      env_file: .env.prod
      ports:
        - ${PORT}:3000
      volumes:
        - ./photos:/app/photos
      networks:
        - twim-network
      depends_on:
        - postgres-db
        - mongo-db
networks:
  twim-network:
    driver: bridge